config/routes.rb
StrHealth::Application.routes.draw do



root 'pages#start'

get '/about' => 'pages#about'

get '/login' => 'sessions#new'
get '/logout' => 'sessions#destroy'
post '/sessions' => 'sessions#create'

get '/start' => 'pages#start'

resources :exercises
resources :workouts
resources :users

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates_presence_of :wo_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


if Rails.env.staging? || Rails.env.production?
    before_filter :authenticate
    def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['HTTP_USERNAME'] && password == ENV['HTTP_PASSWORD']
    end
  end
end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

def about

end

def index
@exercises=Exercise.order(:name)
end


def new
end

def create
end

def show

  @exercise = Exercise.find_by(id: params[:id])

end

def edit
end

def update
end

def destroy
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def about
end

def signin
  end

def start
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def destroy
  reset_session
  redirect_to login_url
end

def create
  user = User.find_by(email: params[:email])
  if user.present?
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to exercises_url
    else
      flash.now[:notice] = "Please try password again."
        render 'new'
    end
  else
    flash.now[:notice] = "Please try email again."
        render 'new'
     #  redirect_to login_url, notice: "Either your login or password does not match our system. Please check the information and try again."
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :set_user, only: [:show, :edit, :update, :destroy]
 before_action :require_login, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.firstname = params[:user][:firstname]
    @user.lastname = params[:user][:lastname]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = @user.password

    if @user.save
      session[:user_id] = @user.id
      redirect_to exercises_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user.firstname = params[:user][:firstname]
    @user.lastname = params[:user][:lastname]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]

    if @user.save
      redirect_to exercises_url
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
  def require_login
    if params[:id] != session[:user_id]
      redirect_to root_url
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find_by(:id => params[:id])
  end

  def new
  end

  def create
    @workout = Workout.new
    @workout.wo_name = params[:wo_name]
    @workout.exercise_id = params[:exercise_id]

    if @workout.save
      redirect_to workouts_url
    else
      @errors = @workout.errors.full_messages
      render 'new'
    end
  end

  def edit
    @workout = Workout.find_by(:id => params[:id])
  end

  def update
    @workout = Workout.find_by(:id => params[:id])
    @workout.wo_name = params[:wo_name]
    @workout.exercise_id = params[:exercise_id]

    if @workout.save
      redirect_to workouts_url
    else
      render 'new'
    end
  end

  def destroy
    @workout = Workout.find_by(:id => params[:id])
    @workout.destroy
    redirect_to workouts_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/exercises/index.html.erb
<div class="container clearfix">
<div class="row">

<% @exercises.each_with_index do |each, i| %>

 <div class="col-md-4">
  <div class=" thumbnail">
    <img src="<%=each[:image]%>" alt="<%=each[:name]%>"
        style="width: 200px; height=100px;" class="img-thumbnail">
    <div class="caption">
      <h5><%=link_to each.name, exercise_url(each.id)%></h5>
      <div class="input-group">
        <span class="input-group-addon">Band Color</span>
        <input type="text" class = "form-control" placeholder ="band-color">
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-sosa dropdown-toggle" data-toggle="dropdown">
          Sets<span class="caret"></span></button>
          <ul class="dropdown-menu" role="menu">
            <li>1</li>
            <li>2</li>
            <li>3</li>
          </ul>
      </div>
      <div class="btn-group">
          <button type="button" class="btn btn-sosa dropdown-toggle" data-toggle="dropdown">
          Reps per set<span class="caret"></span></button>
          <ul class="dropdown-menu" role="menu">
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
            <li>5</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
            <li>10</li>
            <li>11</li>
            <li>12</li>
            <li>13</li>
            <li>14</li>
            <li>15</li>
          </ul>
      </div>
      <button type="button" class="fa fa-star-o">
        Favorite
      </button>
      <p></p>
      <div class="btn-group">
        Date <class="btn btn-default btn-lg">
        <input type="date" placeholder = "<%= Date.today %>" ></input>
        </button>
      </div>
    </div>
  </div>
  <p></p>
 </div>

<% end %>
</div>
</div>

app/views/exercises/show.html.erb
<div class="container">
<div class="jumbotron">
  <h1><%= @exercise[:name] %></h1>
  <button type="button" class="fa fa-star mystar">Favorite</button>
  <p></p>
  <img src="<%= @exercise[:image] %>" alt="<%= @exercise[:name] %>" style="width: 300px; height=200px;">

  <p class="lead" ><%=@exercise[:descr]%></p>
  <p class="tip" > <b>TIP:</b> <%=@exercise[:tip]%></p>
     <div class="btn-group">
      <button type="button" class="btn btn-sosa dropdown-toggle" data-toggle="dropdown"> Sets
        <span class="caret"></span></button>
        <ul class="dropdown-menu" role="menu">
          <li>1</li>
          <li>2</li>
          <li>3</li>
        </ul>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-sosa dropdown-toggle" data-toggle="dropdown"> Reps per set
        <span class="caret"></span></button>
        <ul class="dropdown-menu" role="menu">
          <li>1</li>
          <li>2</li>
          <li>3</li>
          <li>4</li>
          <li>5</li>
          <li>6</li>
          <li>7</li>
          <li>8</li>
          <li>9</li>
          <li>10</li>
          <li>11</li>
          <li>12</li>
          <li>13</li>
          <li>14</li>
          <li>15</li>
        </ul>
    </div>
    <p></p>
    <div class="btn-group">
      Date <class="btn btn-default btn-lg">
      <input type="date" placeholder ></input>
      </button>
    </div>
</div>
<p>

</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Strength and Performance Tracking</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.css" rel="stylesheet">
</head>
<body >


<div class = 'header-wrap clearfix' >
  <nav class="navbar navbar-default" role="navigation">
  <h1 class="sosa"><a href = '/start'><img src="http://www.logomaker.com/logo-images/6c052a6c9d74928c.gif"/></a></h1>

  <% if session[:user_id] %>
    <h3 class="fa fa-user navbar-right"> <%= User.find_by(id: session[:user_id]).firstname %></h3>
      <span><%= link_to "Sign Out", '/logout' %></span>
    <% else %>
    <h3 class="fa fa-user navbar-right"> <%= link_to "Login", "/login" %></h3>
  <% end %>

  <ul class="nav navbar-nav key-button">
    <li class="dropdown">
        <a href="/workouts" class="dropdown-toggle" data-toggle="dropdown">My Favorite Workouts <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">MWF</a></li>
          <li><a href="#">TTHSa</a></li>
          <li><a href="#">PT plan</a></li>
        </ul>
    </li>
    <li><a href="#">My Data Summary</a></li>
    <li> <a href="/exercises">All Exercises </a></li>
    </ul>

  </div>
</nav>
</div>


<%= yield %>

<div class="bs-example bs-navbar-bottom-example">
  <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://drkatewolin.com">Wolin Lab</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-7">
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
         <li><%= link_to "About", about_url%></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources
          <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="http://www.acsm.org">ACSM</a></li>
            <li><a href="http://www.cancer.org">American Cancer Society</a></li>
            <li><a href="http://www.hygenicblog.com/wp-content/uploads/2011/09/Thera-Band-RISE-640x279.jpg">RISE Scale</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class='container about'>
<div class="jumbotron">
<h1>Strength for Health</h1>

<p>Strength for Health is brought to you by the Wolin Laboratory at Loyola Medical School Stritch School of Medicine </p>

<p>The Strength for Health application is designed to help User maintain a healthy lifestyle through better management and tracking of home-based strength training. The Wolin Laboratory and its affiliates have no control over, and makes no representations or warranties, expressed or implied, regarding the use by User or User's healthcare provider(s) of the Strength for Health application or the use or interpretation of any information stored on, generated by or received through the Strength for Health application. User is solely responsible for communicating any injuries or concerns to the User’s healthcare provider(s). </p>

<p>Health Disclaimer:
The strength, performance and fitness information contained herein is provided for general education purposes only. Persons using the data within the Strength for Health pplication for medical purposes, such as to calculate energy expenditure, should not rely solely on the accuracy of the data herein. While the data may be updated periodically, users should independently check other sources for the latest and most accurate information.</p>

<p>
<h6>Contact information:</h6>
The Wolin Laboratory is located in the Maguire Building on the campus of the Loyola University Chicago Medical School at 2160 South First Ave, Maywood, IL.
You can email us at lisa@wolinlab.org
</p>
</div>
</div>

app/views/pages/signin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Signin to Strength for Health</title>


    <div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="form-control" placeholder="Email address" required autofocus>
        <input type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-sosa btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

app/views/pages/start.html.erb
<div class="container">
<div class="jumbotron s4h">
<h2>Getting started</h2>
<p>Increasing your physical activity can be relatively easy, if you know how. One easy way is to incorporate physical activity into your normal routines, like walking rather than driving, taking the stairs instead of the elevator or parking the car farther away from the store. The real challenge is in making the personal commitment to participate in a structured program that will have a significant impact on your overall health. And it needs to become part of your daily routine.</p>

<p>This program focuses on four key parts of a healthy exercise program:</p>

    <ul>
        <li>Knowing your abilities and limitations</li>
        <li>Setting your goals</li>
        <li>Developing your own program</li>
        <li>Monitoring your progress</li>
    </ul>
</p>
<p>Contact your physician if you experience any symptoms of weakness, unsteadiness, light-headedness or dizziness, chest pain or pressure, nausea or shortness of breath. Mild soreness after exercise may be experienced when beginning a new exercise program. Contact your healthcare provider if the soreness does not improve after 2-3 days.</p>

<p>Start with 2-3 activities for each area: upper body, lower body and back. Perform 1 set of 10 repetitions at a resistance that makes you a little tired at the last repetition. Be sure you maintain proper form! Rest for 2 minutes between activities. Maintain normal breathing patterns, breathing once with each repetition. Soreness is to be expected with any time of new activity that isn’t familiar, but it should pass.<br>
<p>Practice your strength exercises 2-3 times per week, and don’t strength train on consecutive days.<br>
Increase repetitions to 15 per activity, then from 1 to 2 sets of each activity. Increase resistance to allow fatigue with the last repetition. As your strength improves, you will notice you will be able to do more activity at the same intensity. You must progressively increase resistance (by changing band color or shortening the band length) to increase strength. You may use different bands for different exercises.<br></p>
You can also use the <a href = 'http://www.hygenicblog.com/wp-content/uploads/2011/09/Thera-Band-RISE-640x279.jpg'>RISE Scale</a> to determine intensity. You should try to maintain a moderate intensity.
</p>

<h2>Progression</h2>
<p>Progression is the key to improving fitness. In general, increase the length or number of the activities before increasing the intensity or difficulty.<br>
Increase the number of times per week the activity is performed increase the length of aerobic activity or number of sets/repetitions<br>
Increase the level by increasing pace for aerobic or adding more resistance (change band color)<br></p>

<h2>Safety</h2>
<p>Contact your doctor if you experience chest pain or pressure, trouble breathing or shortness of breath, light-headedness or dizziness, or nausea with exercise. Don’t perform activities that cause sharp pain or aggravate a medical condition. Muscle soreness is to be expected with any new exercise program.<br>
Use soreness as a guide for intensity. If you are very sore the day after exercising, exercise at a lower intensity next time. If the pain persists more than 2-3 days, contact your healthcare provider. Joint pain, such as in the knees or elbows during exercise, is an indication you should stop and talk to your healthcare provider. Remember to breathe properly. Never hold your breath while straining, particularly if you have high blood pressure. Generally, exhale during muscle exertion, and inhale during relaxation.<br></p>

<h2>Goal Setting</h2>
<p>Goals should be based on your own personal limitations and your preferences. You should write your goals down.<br>
When setting your goals, make sure they are <b>SMART: Specific, Measurable, Attainable, Realistic, and Time-limited</b>. You should be at least 80% sure you can reach your goal for the week. You can revise your goals each week as you make progress. Give yourself a few weeks to get used to your new activities. As you work through your activity, you may find it easier than you thought. Then its time to reevaluate your goals for the following week!<br>
Once you have your goals, you need strategies. Strategies are behaviors to start doing to help you achieve your goals. Examples might be: walk at lunch, use the stairs at work, parking at the far end of the grocery store parking lot. Writing down your behavior strategies will help you use them! Keep an open mind when choosing strategies. You will find some work better than others or you might discover new ones as time goes by.<br>
Refining your goals is a necessary part of this process. When reaching your goals is easy to attain, you want to adjust the goal up. If you didn’t quite meet your goal, you might want to reevaluate both the goal and your strategies.</p>

<h2>
  <%= link_to 'Create a New Workout', new_workout_url %></h2>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>


  <div>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>

  <div>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>

  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.firstname %></td>
      <td><%= user.lastname %></td>
      <td><%= user.email %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Create an Account</h1>


<%= render 'form' %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

app/views/workouts/edit.html.erb
<h1>Editing Workout #<%= @workout.id %></h1>


<%= form_tag(workout_url(@workout), method: 'patch') do %>

  <div>
    <%= label_tag :wo_name %><br />
    <%= text_field_tag :wo_name, @workout.wo_name %>
  </div>

  <div>
    <%= label_tag :exercise_id %><br />
    <%= number_field_tag :exercise_id, @workout.exercise_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Workout" %>
  </div>

<% end %>

app/views/workouts/index.html.erb
<div class = 'container'>
  <div class = 'jumbotron s4h'>
<h1>My Workouts</h1>

<p><%= link_to 'Add a New Workout', new_workout_url %></p>

<table>
  <thead>
    <tr>
      <th>Workout name</th>
      <th>Exercise</th>
       <th>Exercise</th>
        <th>Exercise</th>
         <th>Exercise</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @workouts.each do |workout| %>
    <tr>
      <td><%= workout.wo_name %></td>
      <td><%= workout.exercise_id %></td>
       <td><%= workout.exercise_id %></td>
        <td><%= workout.exercise_id %></td>
         <td><%= workout.exercise_id %></td>
      <td><%= link_to 'Show', workout_url(workout) %></td>
      <td><%= link_to 'Edit', edit_workout_url(workout) %></td>
      <td></td>

    </tr>
  <% end %>
  </tbody>
</table>

</div>
</div>

app/views/workouts/new.html.erb
<h1>Create a New Workout</h1>


<%= form_tag(workouts_url, method: 'post') do %>


  <div>
    <%= label_tag :wo_name , "Workout Name"%><br />
    <%= text_field_tag :wo_name %>
  </div>

  <div>
    <%= label_tag :exercise_id %><br />
    <% exercises = Exercise.all.order("name") %>
    <%= select_tag "exercise_id",
                   options_from_collection_for_select(exercises, :id, :name) %>
  </div>

  <div>
    <%= label_tag :exercise_id %><br />
   <% exercises = Exercise.all.order("name") %>
    <%= select_tag "exercise_id",
                   options_from_collection_for_select(exercises, :id, :name) %>
  </div>

  <div>
    <%= label_tag :exercise_id %><br />
  <% exercises = Exercise.all.order("name") %>
    <%= select_tag "exercise_id",
                   options_from_collection_for_select(exercises, :id, :name) %>
  </div>

  <% if @errors != nil %>
    <% @workout.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
      <% end %>
  <% end %>

  <div>
    <%= submit_tag "Create Workout" %>
  </div>
<% end %>

app/views/workouts/show.html.erb
<h1>Workout #<%= @workout.id %></h1>

<p>
  <b>Workout name:</b>
  <%= @workout.wo_name %>
</p>

<p>
  <b>Exercise:</b>
  <%= @workout.exercise_id %>
</p>

<p>
  <b>Exercise:</b>
  <%= @workout.exercise_id %>
</p>
<p>
  <b>Exercise:</b>
  <%= @workout.exercise_id %>
</p>
<p>
  <b>Exercise:</b>
  <%= @workout.exercise_id %>
</p>
<p>
  <b>Exercise:</b>
  <%= @workout.exercise_id %>
</p>

<%= link_to 'Delete this workout', workout_url(@workout), method: 'delete', data: { confirm: "Do you really want to delete this workout?" } %>